
title: Derek Cresswell
email: derekjcress@gmail.com
github_username:  DerekCresswell
description: >-
  Derek Cresswell's personal website and blog, where I share my thoughts on
  software development, technology, and continuous learning.

domain: derekcresswell.github.io
url: https://derekcresswell.github.io

plugins:
  - jekyll-feed
